/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const computed: typeof import('vue')['computed']
  const defineAsyncComponent: typeof import('vue')['defineAsyncComponent']
  const defineStore: typeof import('pinia')['defineStore']
  const onBeforeRouteLeave: typeof import('vue-router')['onBeforeRouteLeave']
  const onBeforeRouteUpdate: typeof import('vue-router')['onBeforeRouteUpdate']
  const onMounted: typeof import('vue')['onMounted']
  const ref: typeof import('vue')['ref']
  const toRaw: typeof import('vue')['toRaw']
  const toRefs: typeof import('vue')['toRefs']
  const useCounterStore: typeof import('./src/stores/counter')['useCounterStore']
  const useGameStore: typeof import('./src/stores/game')['useGameStore']
  const useLink: typeof import('vue-router')['useLink']
  const useRoute: typeof import('vue-router')['useRoute']
  const useRouter: typeof import('vue-router')['useRouter']
  const watch: typeof import('vue')['watch']
}
