/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./src/App.vue')['default']
    Badge: typeof import('./src/components/common/Badge.vue')['default']
    Banner: typeof import('./src/components/common/Banner.vue')['default']
    Button: typeof import('./src/components/common/Button.vue')['default']
    Card: typeof import('./src/components/common/Card.vue')['default']
    Divider: typeof import('./src/components/common/Divider.vue')['default']
    GameMode: typeof import('./src/views/setup/GameMode.vue')['default']
    GameView: typeof import('./src/views/gameplay/GameView.vue')['default']
    Header: typeof import('./src/components/common/Header.vue')['default']
    HomeView: typeof import('./src/views/HomeView.vue')['default']
    Icon: typeof import('./src/components/common/Icon.vue')['default']
    InputNumber: typeof import('./src/components/common/InputNumber.vue')['default']
    InputText: typeof import('./src/components/common/InputText.vue')['default']
    Link: typeof import('./src/components/common/Link.vue')['default']
    NumberOfQuestions: typeof import('./src/views/setup/NumberOfQuestions.vue')['default']
    Progress: typeof import('./src/components/common/Progress.vue')['default']
    QuestionType: typeof import('./src/views/setup/QuestionType.vue')['default']
    RadioButton: typeof import('./src/components/common/RadioButton.vue')['default']
    RadioGroup: typeof import('./src/components/common/RadioGroup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Score: typeof import('./src/views/setup/Score.vue')['default']
    Welcome: typeof import('./src/views/setup/Welcome.vue')['default']
  }
}
